DROP TABLE IF EXISTS user_authority;
DROP TABLE IF EXISTS authority;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS song;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS playlist;

CREATE TABLE IF NOT EXISTS playlist (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        title VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    genre VARCHAR(255),
    mood VARCHAR(255),
    is_public BOOLEAN,
    created_at TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS review (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      playlist_id BIGINT,
                                      playlist_title VARCHAR(500),
                                      rating INT,
                                      comment VARCHAR(500),
    reviewed_at TIMESTAMP,
    FOREIGN KEY (playlist_id) REFERENCES playlist(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS song (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            playlist_id BIGINT NOT NULL,
                                            name VARCHAR(255) NOT NULL,
    artist VARCHAR(255),
    album VARCHAR(255),
    duration_seconds DECIMAL(10, 2),
    FOREIGN KEY (playlist_id) REFERENCES playlist(id) ON DELETE CASCADE
    );


CREATE TABLE IF NOT EXISTS app_user (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS authority (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(255) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS user_authority (
                                              user_id BIGINT,
                                              authority_id BIGINT,
                                              FOREIGN KEY (user_id) REFERENCES app_user(id),
    FOREIGN KEY (authority_id) REFERENCES authority(id)
    );